infinity ward
infinity ward, sledge hammar studios

gamesales2010_2016 <- filter(gamesales2010_2016, Developer != "NA")

Nintendo
Nintendo EAD Tokyo o

gamesales2010_2016$Developer <- recode(gamesales2010_2016$Developer,"1C Company" = "1C: Maddox Games", "1C Company" = "1C:Ino-Co","2K Australia" = "2K Sports", "2K Czech" = "2K Sports", "2K Games" = "2K Sports", "2K Marin" = "2K Sports", "2K Play" = "2K Sports", "505 Games, Sarbakan Inc." = "505 Games", "Activision, Behaviour Interactive" = "Activision", "Activision, FreeStyleGames" = "Activision", "Ambrella, The Pokemon Company" = "Ambrella", "Armature Studio, comcept" = "Armature Studio", "Artificial Mind and Movement, EA Redwood Shores" = "Artificial Mind and Movement", "Atari, Atari SA" = "Atari", "Atari, Slightly Mad Studios, Atari SA" = "Atari", "Atlus, Dingo Inc." = "Atlus", "Atomic Planet Entertainment" = "Atomic Games", "Avalanche Software" = "Avalanche Studios", "Bandai Namco Games, Artdink" = "Bandai Namco Games", "Beenox, Other Ocean Interactive" = "Beenox", "Big Blue Bubble Inc., Scholastic, Inc." = "Big Blue Bubble Inc.", "Big Blue Bubble Inc., Scholastic, Inc." = "Big Blue Bubble Inc.", "Blitz Games Studios" = "Blitz Games", "Blue Byte, Related Designs" = "Blue Byte", "Bungie Software, Bungie" = "Bungie", "Capcom Vancouver" = "Capcom", "Capcom, Pipeworks Software, Inc." = "Capcom",                             
"Capcom, QLOC" = "Capcom", "Climax Entertainment" = "Climax Studios", "Climax Group" = "Climax Studios", "Climax Group, Climax Studios" = "Climax Studios", "Codemasters Birmingham" = "Codemasters", "Compile Heart, GCREST" = "Compile Heart", "Crave, DTP Entertainment" = "Crave", "Crystal Dynamics, Nixxes Software" = “Crystal Dynamics", 
"Cyanide, Cyanide Studios" = "Cyanide", "CyberConnect2, Racjin" = "CyberConnect2", "CyberPlanet Interactive Public Co., Ltd., Maximum Family Games" = "CyberPlanet Interactive Public Co., Ltd.", "Deep Silver Dambuster Studios" = “Deep Silver”, "Deep Silver, Keen Games" = “Deep Silver”, "Dimps Corporation, Dream Execution" = "Dimps Corporation”, "Dimps Corporation, SCE Japan Studio" = "Dimps Corporation”, "Disney Interactive Studios, Land Ho!" = "Disney Interactive Studios”, "EA Black Box" = "EA Games", "EA Bright Light" = "EA Games", "EA Canada" = "EA Games", "EA Canada, EA Vancouver” = "EA Games" , "EA DICE" = "EA Games", "EA DICE, Danger Close" = "EA Games", “EA Sports" = “EA Games”, "EA Montreal" = “EA Games”, "EA Redwood Shores" = “EA Games”, "EA Sports, EA Canada" = “EA Games”, "EA Sports, EA Vancouver" = “EA Games”, "EA Tiburon” = “EA Games”, "Eidos Montreal, Nixxes Software" = Eidos Montreal", "Engine Software, Re-Logic" = “Engine Software", "Epic Games, People Can Fly” = “Epic Games”, "Farsight Studios, Crave" = "Farsight Studios",  "Gaijin Entertainment" = "Gaijin Games", "Gearbox Software, 3D Realms" = "Gearbox Software”, "Gearbox Software, WayForward" = "Gearbox Software”, "Guerilla Cambridge" = "Guerrilla Cambridge", "Guerilla" = “ "Guerilla Cambridge", “Harmonix Music Systems, Demiurge” = “Harmonix Music Systems", "Headup Games, Crenetic Studios" = "Headup Games", "Konami Computer Entertainment Hawaii” = “Konami”, "Marvelous AQL" = "Marvelous Inc.", "Marvelous Entertainment" = "Marvelous Inc.", "Midway Studios - Austin" = "Midway", "Monolith Soft" = "Monolith Productions”, "Monolith Soft, Banpresto" = “Monolith Productions”, "Namco Bandai Games America, Namco Bandai Games" = "Namco Bandai Games", "Namco Bandai Games, Bandai Namco Games" = "Namco Bandai Games", "Namco Bandai Games, Cellius" = "Namco Bandai Games", "Namco Bandai Games, Monkey Bar Games" = "Namco Bandai Games", "NATSUME ATARI Inc." = “Natsume”, "Nintendo EAD Tokyo" = "Nintendo", "Nintendo, Camelot Software Planning" = "Nintendo", "Nintendo, Headstrong Games" = "Nintendo", "Nintendo, Intelligent Systems" = "Nintendo", "Nintendo, Nd Cube" = "Nintendo", "Nintendo, Nintendo Software Technology" = "Nintendo","Nintendo, Spike Chunsoft" = "Nintendo", "Paradox Development Studio" = "Paradox Interactive", "PLAYGROUND, Playground Games" = "Playground Games", "Retro Studios, Entertainment Analysis & Development Division" = “Retro Studios", "Rockstar Leeds" = "Rockstar Studios", "Rockstar North" = "Rockstar Studios", "Rockstar San Diego" = "Rockstar Studios, "Sanzaru Games, Sanzaru Games, Inc." = "Sanzaru Games", "SCE Japan Studio, comcept" = "SCE Studio”, "SCE Santa Monica" = "SCE Studio”, "SCE Studio Cambridge" = "SCE Studio, "SCE Japan Studio” = “SCE Studio”, "SCEA San Diego Studios" = "SCEA","SCEA, Zindagi Games” = "SCEA", "SCEE London Studio" = “SCEE”

 )


```{r}
gamesales2010_2016$Developer <- recode(gamesales2010_2016$Developer,"1C Company" = "1C: Maddox Games", "1C Company" = "1C:Ino-Co","2K Australia" = "2K Sports", "2K Czech" = "2K Sports", "2K Games" = "2K Sports", "2K Marin" = "2K Sports", "2K Play" = "2K Sports", "505 Games, Sarbakan Inc." = "505 Games", "Activision, Behaviour Interactive" = "Activision", "Activision, FreeStyleGames" = "Activision", "Ambrella, The Pokemon Company" = "Ambrella", "Armature Studio, comcept" = "Armature Studio", "Artificial Mind and Movement, EA Redwood Shores" = "Artificial Mind and Movement", "Atari, Atari SA" = "Atari", "Atari, Slightly Mad Studios, Atari SA" = "Atari", "Atlus, Dingo Inc." = "Atlus", "Atomic Planet Entertainment" = "Atomic Games", "Avalanche Software" = "Avalanche Studios", "Bandai Namco Games, Artdink" = "Bandai Namco Games", "Beenox, Other Ocean Interactive" = "Beenox", "Big Blue Bubble Inc., Scholastic, Inc." = "Big Blue Bubble Inc.", "Big Blue Bubble Inc., Scholastic, Inc." = "Big Blue Bubble Inc.", "Blitz Games Studios" = "Blitz Games", "Blue Byte, Related Designs" = "Blue Byte", "Bungie Software, Bungie" = "Bungie", "Capcom Vancouver" = "Capcom", "Capcom, Pipeworks Software, Inc." = "Capcom",                             
                                       "Capcom, QLOC" = "Capcom", "Climax Entertainment" = "Climax Studios", "Climax Group" = "Climax Studios", "Climax Group, Climax Studios" = "Climax Studios", "Codemasters Birmingham" = "Codemasters", "Compile Heart, GCREST" = "Compile Heart", "Crave, DTP Entertainment" = "Crave", "Crystal Dynamics, Nixxes Software" = "Crystal Dynamics", "Cyanide, Cyanide Studios" = "Cyanide", "CyberConnect2, Racjin" = "CyberConnect2", "CyberPlanet Interactive Public Co., Ltd., Maximum Family Games" = "CyberPlanet Interactive Public Co., Ltd.", "Deep Silver Dambuster Studios" = "Deep Silver", "Deep Silver, Keen Games" = "Deep Silver", "Dimps Corporation, Dream Execution" = "Dimps Corporation", "Dimps Corporation, SCE Japan Studio" = "Dimps Corporation", "Disney Interactive Studios, Land Ho!" = "Disney Interactive Studios", "EA Black Box" = "EA Games", "EA Bright Light" = "EA Games", "EA Canada" = "EA Games", "EA Canada, EA Vancouver" = "EA Games" , "EA DICE" = "EA Games", "EA DICE, Danger Close" = "EA Games", "EA Sports" = "EA Games", "EA Montreal" = "EA Games", "EA Redwood Shores" = "EA Games", "EA Sports, EA Canada" = "EA Games", "EA Sports, EA Vancouver" = "EA Games", "EA Tiburon” = “EA Games", "Eidos Montreal, Nixxes Software" = "Eidos Montreal", "Engine Software, Re-Logic" = "Engine Software", "Epic Games, People Can Fly" = "Epic Games", "Farsight Studios, Crave" = "Farsight Studios",  "Gaijin Entertainment" = "Gaijin Games", "Gearbox Software, 3D Realms" = "Gearbox Software", "Gearbox Software, WayForward" = "Gearbox Software", "Guerilla Cambridge" = "Guerrilla Cambridge", "Guerilla" = "Guerilla Cambridge", "Harmonix Music Systems, Demiurge” = “Harmonix Music Systems", "Headup Games, Crenetic Studios" = "Headup Games", "Konami Computer Entertainment Hawaii" = "Konami", "Marvelous AQL" = "Marvelous Inc.", "Marvelous Entertainment" = "Marvelous Inc.", "Midway Studios - Austin" = "Midway", "Monolith Soft" = "Monolith Productions", "Monolith Soft, Banpresto" = "Monolith Productions", "Namco Bandai Games America, Namco Bandai Games" = "Namco Bandai Games", "Namco Bandai Games, Bandai Namco Games" = "Namco Bandai Games", "Namco Bandai Games, Cellius" = "Namco Bandai Games", "Namco Bandai Games, Monkey Bar Games" = "Namco Bandai Games", "NATSUME ATARI Inc." = "Natsume", "Nintendo EAD Tokyo" = "Nintendo", "Nintendo, Camelot Software Planning" = "Nintendo", "Nintendo, Headstrong Games" = "Nintendo", "Nintendo, Intelligent Systems" = "Nintendo", "Nintendo, Nd Cube" = "Nintendo", "Nintendo, Nintendo Software Technology" = "Nintendo","Nintendo, Spike Chunsoft" = "Nintendo", "Paradox Development Studio" = "Paradox Interactive", "PLAYGROUND, Playground Games" = "Playground Games", "Retro Studios, Entertainment Analysis & Development Division" = "Retro Studios", "Rockstar Leeds" = "Rockstar Studios", "Rockstar North" = "Rockstar Studios", "Rockstar San Diego" = "Rockstar Studios", "Sanzaru Games, Sanzaru Games, Inc." = "Sanzaru Games", "SCE Japan Studio, comcept" = "SCE Studio", "SCE Santa Monica" = "SCE Studio", "SCE Studio Cambridge" = "SCE Studio", "SCE Japan Studio" = "SCE Studio", "SCEA San Diego Studios" = "SCEA","SCEA, Zindagi Games" = "SCEA", "SCEE London Studio" = "SCEE",
"Sega Studios San Francisco" = "Sega", "Sega Toys" = "Sega", "Sega, Dimps Corporation" = "Sega", "Sega, French-Bread" = "Sega", "Sega, Sonic Team" = "Sega", "Snapdragon" = "Snap Dragon Games", "Sonic Team" = "Sega", "Sony Bend" = "Sony Interactive Entertainment", "Sony Online Entertainment" = "Sony Interactive Entertainment", "Spike Chunsoft" = "Spike", "Spike Chunsoft Co. Ltd., Spike Chunsoft" = "Spike","Tecmo" = "Tecmo Koei Games", "Tecmo Koei Canada" = "Tecmo Koei Games", "THQ Australia" = "THQ", "THQ Digital Studio Phoenix" = "THQ", "Ubisoft Casablanca" = "Ubisoft", "Ubisoft Milan" = "Ubisoft", "Ubisoft Montpellier" = "Ubisoft", "Ubisoft Montreal" = "Ubisoft", "Ubisoft Osaka" = "Ubisoft", "Ubisoft Paris" = "Ubisoft", "Ubisoft Paris, Ubisoft Montpellier" = "Ubisoft", "Ubisoft Quebec" = "Ubisoft", "Ubisoft Reflections" = "Ubisoft", "Ubisoft Reflections, Ivory Tower" = "Ubisoft", "Ubisoft Romania" = "Ubisoft", "Ubisoft Sofia" = "Ubisoft", "Ubisoft Toronto" = "Ubisoft", "Ubisoft Vancouver" = "Ubisoft", "Ubisoft, FunHouse" = "Ubisoft", "Ubisoft, Ludia Inc." = "Ubisoft", "Ubisoft, Ubisoft Montreal" = "Ubisoft")    

```